version: "3.3"

services:
  km-hmi-test:
    build:
      context: docker/hmi_apache_server
      dockerfile: docker/hmi_apache_server/Dockerfile
    ports:
      - "92:80"
    volumes:
      - ./environments/test/hmi_apacheconf/sites/:/usr/local/apache2/conf/sites
      - ./../web/build/:/usr/local/apache2/techolaf


