version: "3.8"

services:
  apache:
    image: httpd:latest
    # restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # config
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
#       SSL certificates
      - ./certs/:/etc/ssl/certs
      # Website static files can be placed here.
      - ./ui/:/usr/local/htdocs/

      - ./environments/example/hmi_apacheconf/sites/:/usr/local/apache2/conf/sites
      - ./ui/:/usr/local/apache2/navy
